In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

In [23]:
url ='https://raw.githubusercontent.com/ritabratamaiti/Autism-Detection-API/master/ASD_Data.csv'
data = pd.read_csv(url)
data.head()

Unnamed: 0  q1  q2  q3  q4  q5  q6  q7  q8  q9    ...      score   age  \
0           0   1   1   0   1   0   0   0   1   0    ...          5  24.0   
1           1   1   1   0   1   1   0   1   1   1    ...          8  27.0   
2           2   1   1   0   1   0   0   1   1   0    ...          6  35.0   
3           3   1   0   0   0   0   0   0   1   0    ...          2  40.0   
4           4   1   1   1   1   1   0   1   1   1    ...          9  36.0   

   gender            race bornwithjaundice familymemberwithpdd  \
0       m          Latino               no                 yes   
1       m          Latino              yes                 yes   
2       f  White-European               no                 yes   
3       f               0               no                  no   
4       m          Others              yes                  no   

  placeofresidence usedscreeningbefore Whoistakingthetest HasAutism?  
0           Brazil                  no               Self         NO  
1            Spain                  no             Parent        YES  
2    United States                  no               Self         NO  
3            Egypt                  no                  0         NO  
4    United States                  no               Self        YES  

[5 rows x 21 columns]

In [24]:
data.drop(["Unnamed: 0"],axis=1,inplace=True)

In [25]:
data.head()

q1  q2  q3  q4  q5  q6  q7  q8  q9  q10  score   age gender  \
0   1   1   0   1   0   0   0   1   0    1      5  24.0      m   
1   1   1   0   1   1   0   1   1   1    1      8  27.0      m   
2   1   1   0   1   0   0   1   1   0    1      6  35.0      f   
3   1   0   0   0   0   0   0   1   0    0      2  40.0      f   
4   1   1   1   1   1   0   1   1   1    1      9  36.0      m   

             race bornwithjaundice familymemberwithpdd placeofresidence  \
0          Latino               no                 yes           Brazil   
1          Latino              yes                 yes            Spain   
2  White-European               no                 yes    United States   
3               0               no                  no            Egypt   
4          Others              yes                  no    United States   

  usedscreeningbefore Whoistakingthetest HasAutism?  
0                  no               Self         NO  
1                  no             Parent        YES  
2                  no               Self         NO  
3                  no                  0         NO  
4                  no               Self        YES

In [26]:
for i in range(len(data['gender'])):
  if data['gender'][i] =='m':
    data['gender'][i] =1
  else:
    data['gender'][i] = 0
  

G:\Anaconda\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
G:\Anaconda\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """


In [27]:
dic = {'yes':1,'no':0}
data['bornwithjaundice'].replace(dic,inplace=True)

In [28]:
data['familymemberwithpdd'].replace(dic,inplace=True)

In [29]:
data['usedscreeningbefore'].replace(dic,inplace=True)

In [30]:
dic = {'YES':1,'NO':0}
data['HasAutism?'].replace(dic,inplace=True)

In [31]:
data.head()

q1  q2  q3  q4  q5  q6  q7  q8  q9  q10  score   age gender  \
0   1   1   0   1   0   0   0   1   0    1      5  24.0      1   
1   1   1   0   1   1   0   1   1   1    1      8  27.0      1   
2   1   1   0   1   0   0   1   1   0    1      6  35.0      0   
3   1   0   0   0   0   0   0   1   0    0      2  40.0      0   
4   1   1   1   1   1   0   1   1   1    1      9  36.0      1   

             race  bornwithjaundice  familymemberwithpdd placeofresidence  \
0          Latino                 0                    1           Brazil   
1          Latino                 1                    1            Spain   
2  White-European                 0                    1    United States   
3               0                 0                    0            Egypt   
4          Others                 1                    0    United States   

   usedscreeningbefore Whoistakingthetest  HasAutism?  
0                    0               Self           0  
1                    0             Parent           1  
2                    0               Self           0  
3                    0                  0           0  
4                    0               Self           1

In [33]:
#data.drop(['Whoistakingthetest','usedscreeningbefore','race','placeofresidence'],axis=1,inplace=True)

data.head()

q1  q2  q3  q4  q5  q6  q7  q8  q9  q10  score   age gender  \
0   1   1   0   1   0   0   0   1   0    1      5  24.0      1   
1   1   1   0   1   1   0   1   1   1    1      8  27.0      1   
2   1   1   0   1   0   0   1   1   0    1      6  35.0      0   
3   1   0   0   0   0   0   0   1   0    0      2  40.0      0   
4   1   1   1   1   1   0   1   1   1    1      9  36.0      1   

   bornwithjaundice  familymemberwithpdd  HasAutism?  
0                 0                    1           0  
1                 1                    1           1  
2                 0                    1           0  
3                 0                    0           0  
4                 1                    0           1

In [114]:
from sklearn.model_selection import train_test_split,RepeatedKFold


In [35]:
data.columns

Index(['q1', 'q2', 'q3', 'q4', 'q5', 'q6', 'q7', 'q8', 'q9', 'q10', 'score',
       'age', 'gender', 'bornwithjaundice', 'familymemberwithpdd',
       'HasAutism?'],
      dtype='object')

In [36]:
x= data.iloc[: , :15].values
y = data.iloc[: , 15].values

In [39]:
x[0].shape

(15,)

In [40]:
 X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [119]:
kf = RepeatedKFold(n_splits=5, n_repeats=10, random_state=None) 

for train_index, test_index in kf.split(x):
      X_train, X_test = x[train_index], x[test_index] 
      y_train, y_test = y[train_index], y[test_index]

In [121]:
from sklearn.svm import SVC

In [122]:
svc = SVC()

In [123]:
svc.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [124]:
pred = svc.predict(X_test)

In [125]:
from sklearn.metrics import classification_report

In [126]:
print(classification_report(y_test,pred))

             precision    recall  f1-score   support

          0       1.00      0.99      0.99        98
          1       0.98      1.00      0.99        42

avg / total       0.99      0.99      0.99       140



In [127]:
val = svc.predict([[1,0,1,0,1,1,1,0,0,0,5,15.0,1,0,0]])

In [128]:
val

array([0], dtype=int64)

In [129]:
import pickle

In [131]:
pickle.dump(data,open('ASD_dataset','wb'))

In [27]:
d = pickle.load(open('ASD_dataset','rb'))

In [130]:
pickle.dump(svc,open('ASD_model','wb'))

In [0]:
import os


In [110]:
os.path.abspath('detection of ASD.ipynb')

'/content/detection of ASD.ipynb'

In [4]:
model = pickle.load(open('ASD_model','rb'))

In [13]:
from flask import Flask,jsonify,request
import numpy as np
import pandas as pd
import pickle
app = Flask(__name__)

In [17]:
@app.route('/ASD_detection', methods=['POST'])
def apicall():
    try:
        json = request.get_json()
        test = pd.read_json(json,orient='records')
    except Exception as e:
        raise e
    if test.empty:
        return(bad_request())
    else:
        model = None
        with open('ASD_model','rb') as f:
            model = pickle.load(f)
        pred = model.predict(test)
        if pred == 1:
            pred_text = 'HAS ASD'
        else :
            pred_text = "No ASD"
        response = jsonify(pred_text.to_json(orient='records'))
        response.status_code = 200
        return (response)

In [3]:
import requests,json

In [64]:
url = 'http://127.0.0.1:5000/ASD_detection'
data = json.dumps({'q1':1,'q2':1,'q3':0,'q4':0,'q5':1,'q6':1,'q7':0,'q8':0,'q9':0,'q10':0,'score':7,'age':15,'gen':1,'bwj':1,'fmpd':0})

In [65]:
r = requests.post(url,data)

In [66]:
print(r.json())

{'results': 'No'}


In [106]:
X_test[3]

array([1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 7, 40.0, 0, 1, 1], dtype=object)

In [4]:
import pickle

In [5]:
model = pickle.load(open('ASD_model','rb'))

In [6]:
pred = model.predict([[1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 5, 40.0, 0, 1, 1]])

In [7]:
pred

array([0], dtype=int64)

In [107]:
pred1 = model.predict([[1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 7, 40.0, 0, 1, 1]])

In [108]:
pred1

array([1], dtype=int64)

In [8]:
model_json = model.to_json()

AttributeError: 'SVC' object has no attribute 'to_json'